version: "3"
services:
  exchanges_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: exchanges_api
    restart: unless-stopped
    ports:
      - "${DOCKER_PORT}:${DOCKER_PORT}"
    environment:
      PORT: ${DOCKER_PORT}
      #MONGODB_URI: mongodb://mongo_container_bot:27017/
      #MONGODB_URI: mongodb://172.31.26.81:27017/
      MONGODB_URI: ${MONGOURL}
      PAPER_URL: ${PAPER_URL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      PAPER_PORT:
    volumes:
      - exchanges_api:/data/db
volumes:
  exchanges_api:
logging:
  driver: "awslogs"
  options:
    awslogs-region: "us-east-1"
    awslogs-group: "mygroup"
    tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
