version: "3"
services:
  exchanges_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: exchanges_api
    restart: unless-stopped
    ports:
      - "$${PORT}:$${PORT}"
    environment:
      PORT: $${PORT}
      #MONGODB_URI: mongodb://mongo_container_bot:27017/
      #MONGODB_URI: mongodb://172.31.26.81:27017/
      MONGODB_URI: $${MONGOURL}
      DB_NAME: $${DBNAME}
      PAPER_URL: $${PAPER_URL}
      PAPER_PORT:
    volumes:
      - exchanges_api:/data/db
volumes:
  exchanges_api: